[package]
name = "dotconfig"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
dirs = "6.0.0"
serde = { version = "1.0", features = ["derive"] }
ron = "0.12"
which = "8.0.0"

[[bin]]
name = "dotconfig"
path = "dotconfig.rs"

# We use `opt-level = "s"` as it significantly reduces binary size.
# We could then use the `#[optimize(speed)]` attribute for spot optimizations.
# Unfortunately, that attribute currently doesn't work on intrinsics such as memset.
[profile.release]
lto = true # reduces binary size
panic = "abort" # reduces binary size
split-debuginfo = "packed" # generates a separate *.dwp/*.dSYM so the binary can get stripped
strip = "symbols" # See split-debuginfo - allows us to drop the binary size
opt-level = "z" # reduces binary size to under 1MB
incremental = true # Improves re-compile times
