#!/usr/bin/env php
<?php

require_once 'dotconfig_setup.php';

$home = $_SERVER["HOME"];

dotLink("Sublime/User", "{$home}/Library/Application Support/Sublime Text/Packages/User");
dotLink("Sublime/Installed Packages", "{$home}/Library/Application Support/Sublime Text/Installed Packages");
