export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="robbyrussell"

plugins=(git laravel)

source $ZSH/oh-my-zsh.sh

export PATH=$PATH:$HOME/go/bin
export EDITOR="nvim"

# bun completions
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

if [[ `uname` == Darwin ]]; then
  # Sublime Text
  export PATH="$PATH:/Applications/Sublime Text.app/Contents/SharedSupport/bin"

  export PATH="/usr/local/share/dotnet:$PATH"

  # Herd injected PHP binary.
  export PATH="$HOME/Library/Application Support/Herd/bin/":$PATH

  # Herd injected PHP 8.5 configuration.
  export HERD_PHP_85_INI_SCAN_DIR="/Users/cristianbilu/Library/Application Support/Herd/config/php/85/"

  # Herd injected PHP 8.4 configuration.
  export HERD_PHP_84_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/84/"

  # Herd injected PHP 8.3 configuration.
  export HERD_PHP_83_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/83/"

  # Herd injected PHP 8.2 configuration.
  export HERD_PHP_82_INI_SCAN_DIR="$HOME/Library/Application Support/Herd/config/php/82/"

  # Herd injected NVM configuration
  export NVM_DIR="$HOME/Library/Application Support/Herd/config/nvm"

  [[ -f "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh" ]] && builtin source "/Applications/Herd.app/Contents/Resources/config/shell/zshrc.zsh"

  export LDFLAGS="-L$(brew --prefix)/lib"
  export CPPFLAGS="-I$(brew --prefix)/include/"

  # Composer
  export PATH="$HOME/.composer/vendor/bin:$PATH"

  export VCPKG_ROOT="$HOME/vcpkg"
  export PATH="$VCPKG_ROOT:$PATH"
  export ODIN_ROOT=$HOME/src/odin/Odin
else
  export ODIN_ROOT=/usr/lib/odin
  export NVM_DIR="$HOME/.nvm"
  export PATH=~/.config/emacs/bin:$PATH
fi

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$PATH:$ODIN_ROOT

alias wip="git add .; git commit -m \"WIP\""
alias gip="git push"
alias gis="git status"
alias vim="nvim"
alias ls="exa"
alias la="ls -la"
alias grep="rg"
alias ta="tmux a"

TIMEFMT='%J   %U  user %S system %P cpu %*E total'$'\n'\
'avg shared (code):         %X KB'$'\n'\
'avg unshared (data/stack): %D KB'$'\n'\
'total (sum):               %K KB'$'\n'\
'max memory:                %M KB'$'\n'\
'page faults from disk:     %F'$'\n'\
'other page faults:         %R'

. "$HOME/.cargo/env"

if [[ `uname` == Linux ]]; then
  # php.new
  export PATH="/home/cristian/.config/herd-lite/bin:$PATH"
  export PHP_INI_SCAN_DIR="/home/cristian/.config/herd-lite/bin:$PHP_INI_SCAN_DIR"
fi

if (( ${+WSLENV} )); then
  alias ssh=ssh.exe
fi

# Let this be last
eval "$(starship init zsh)"

export PATH="$HOME/.local/bin:$PATH"

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
